[package]
name = "native_spark"
version = "0.1.0"
authors = ["raja <rajasekar3eg@gmail.com>"]
edition = "2018"

build = "build.rs"

[lib]
name = "native_spark"

[dependencies]
actix-web = "1.0.9"
env_logger = "0.7.1"
fasthash = "0.4.0"
itertools = "0.8.1"
num_cpus = "1.11.1"
log = "0.4.8"
reqwest = "0.9.22"
once_cell = "1.2.0"
parking_lot = { version = "0.9.0", features = ["serde"] }
simplelog = "0.7.4"
thiserror = "1.0"
threadpool = "1.7.1"
toml = "0.5.5"
uuid = { version = "0.8", features = ["v4"] }

# randomness
rand = "0.7"
rand_distr = "0.2"
rand_pcg = "0.2"

# serialization
bincode = "1.2.0"
capnp = "0.10.3"
serde = { version = "1.0.102", features = ["rc"] }
serde_closure = "0.2"
serde_derive = "1.0.102"

# dynamic typing
downcast-rs = "1.1.1"
objekt = "0.1.2"
serde_traitobject = "0.2"

[dependencies.clap]
version = "2.33"
default-features = false

[build-dependencies]
capnpc = "0.10.1"

[dev-dependencies]
chrono = "0.4"
parquet = "0.15.1"
tempfile = "3"
